elasticsearch:
  extends:
    file: docker-compose-base.yml
    service: elasticsearch
  build: elasticsearch
logstash:
  extends:
    file: docker-compose-base.yml
    service: logstash
  build: logstash
  links:
    - elasticsearch:elasticsearch
kibana:
  extends:
    file: docker-compose-base.yml
    service: kibana
  build: kibana
  links:
    - elasticsearch:elasticsearch
